// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6pnXRVYn_Re5dV1Op1umKHfrw5fvmgKo',
    appId: '1:480673739792:web:6f3512fef690dee6d04695',
    messagingSenderId: '480673739792',
    projectId: 'e-commerce-c472f',
    authDomain: 'e-commerce-c472f.firebaseapp.com',
    storageBucket: 'e-commerce-c472f.appspot.com',
    measurementId: 'G-PKD0SZR9Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomgCT3CSVdswtmfQEgvWk18uWuf9lk40',
    appId: '1:480673739792:android:107531e77e4962f9d04695',
    messagingSenderId: '480673739792',
    projectId: 'e-commerce-c472f',
    storageBucket: 'e-commerce-c472f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8u5XHNAWUCYkq6bSWkE8yZqA77GtDzkA',
    appId: '1:480673739792:ios:4a10ce4bb3c5ab96d04695',
    messagingSenderId: '480673739792',
    projectId: 'e-commerce-c472f',
    storageBucket: 'e-commerce-c472f.appspot.com',
    iosBundleId: 'com.pollex.ecommerce',
  );
}
